### ISSUE TITLE
같은 페이지 내에서 쿠키 사이즈 다름

### ISSUE THREAD

**Issue by sbyeol3** [Nexters/BRUNO#65]
<img width="418" alt="스크린샷 2022-03-26 오후 4 59 49" src="https://user-images.githubusercontent.com/43198553/160230526-6d129179-8e08-4380-9a6c-9d4b5e9f31f8.png">

**Comment by sewonkimm** [comment]
https://www.notion.so/lizzie00/49ba4b3093ae408a83b5c5db89c43a1b
