### ISSUE TITLE
숨기기 박스 미노출

### ISSUE THREAD

**Issue by sbyeol3** [Nexters/BRUNO#66]
<img width="418" alt="스크린샷 2022-03-26 오후 4 59 49" src="https://user-images.githubusercontent.com/43198553/160230526-6d129179-8e08-4380-9a6c-9d4b5e9f31f8.png">

- 항상 재현되는 이슈 아님
- 어떤 환경에서 재현되는지 확인 필요

**Comment by sewonkimm** [comment]
https://www.notion.so/lizzie00/49ba4b3093ae408a83b5c5db89c43a1b
